### ISSUE TITLE
1.1.0 breaks Craft 3

### ISSUE THREAD

**Issue by DowleyDeveloped** [wmdhosting/craft3-section-and-product-type-field#2]
If updated on a Craft 3 install, this causes a fatal error due to updates for Craft 4.

**Comment by wmdhosting** [comment]
OK thx for info..   can you downgrade....  this time.. 
as will not update anything for Craft3 anymore..

Developer will leave info next time :)

**Comment by DowleyDeveloped** [comment]
Could you change the version of Craft needed in composer so the option to update doesn't display in Craft 3?

**Comment by wmdhosting** [comment]
Yes, developer will change . today.

**Comment by danfathom** [comment]
I've just had the same issue. I had to update all plugins and leave this one on version 1.0.5.

**Comment by wmdhosting** [comment]
Sorry, developer was absent, will come tomorow, hope and resolve that..

**Comment by wmdhosting** [comment]
Its done now.
