### ISSUE TITLE
PHP compile error when installing v1.1.0 on Craft 3.7.63

### ISSUE THREAD

**Issue by samiramer** [wmdhosting/craft3-section-and-product-type-field#3]
Using this plugin with Craft 3 will install v1.1.0.

The plugin crashes, resulting  in a PHP compile error 

```
Error Output:
================
PHP Compile Error 'yii\base\ErrorException' with message 'Type of wmd\sectionandproducttype\SectionAndProductType::$schemaVersion must not be defined (as in class craft\base\Plugin)'
```

This is happening because the Plugin.php file is using type hinted properties.  This is a Craft 4 change.  

The base Plugin class in Craft 3 does not have type hinted props.

Plugin.php in this package: https://github.com/wmdhosting/craft3-section-and-product-type-field/blob/2dff7726b83ed4b31dbdca590cd34e4bf0dc8816/src/SectionAndProductType.php#L27

Plugin.php in Craft 3: 
https://github.com/craftcms/cms/blob/c031ebc215d421b047fd89b19b0505b0826a7123/src/base/PluginTrait.php#L31

**Comment by jozoXXL** [comment]
Developer coming back tuesday. 
If you need faster. you can try  1.0.5 version

**Comment by samiramer** [comment]
FYI I have reverted back to 1.0.5

**Comment by wmdhosting** [comment]
ok thx for info.  i fowareded to devloper but seems he was too busy..
