### ISSUE TITLE
Section View Permissions are ignored 

### ISSUE THREAD

**Issue by handplant** [wmdhosting/craft3-section-and-product-type-field#4]
I have multiple news sections and would like to integrate them into the 'Sections' field. So far, so good. However, some user groups do not have the 'View' permission for all these sections. Could you integrate it so that these sections are only displayed if the user has the 'View' rights? 

Something like this: `$currentUser->can("viewEntries:{$section->uid}")`

Thank you!

**Comment by wmdhosting** [comment]
will check with developer, 

that is for Craft 4 or Craft 5...?

**Comment by handplant** [comment]
Craft 5, thx!

**Comment by wmdhosting** [comment]
I just tested and works ok.. user see only sections that have rights for...
Did you test with user account...

**Comment by handplant** [comment]
I have tested it with the user account. I attached a screenshot with the permissions and another screenshot with the user and the field.

![Bildschirmfoto 2024-03-14 um 09 05 06](https://github.com/wmdhosting/craft3-section-and-product-type-field/assets/2598962/4fd83cfa-2ff7-4e7c-b625-89cea077a252)
![Bildschirmfoto 2024-03-14 um 09 05 29](https://github.com/wmdhosting/craft3-section-and-product-type-field/assets/2598962/70077893-0cc9-47c0-b7ce-244527150deb)

**Comment by wmdhosting** [comment]
Something strange here. . as  you have Hessen section. too and not shown.in Section field..

**Comment by handplant** [comment]
Yes, I forgot to configure it in the field.

![Bildschirmfoto 2024-03-14 um 09 23 18](https://github.com/wmdhosting/craft3-section-and-product-type-field/assets/2598962/89fc6fa3-d9aa-4999-98fb-4761cb278ca0)

**Comment by wmdhosting** [comment]
Can you try like this.. 

**>>> Select All Sections**

This will allow all sections to be used for selection.
as you use exclude settings 

As now you manually selected  Allowed section.. 
so think that is oweriding .. User view righs..

**Comment by handplant** [comment]
Unfortunately no, the same result.
I can't find anything in your code that checks the permissions either.

**Comment by wmdhosting** [comment]
Ok will check with developer .. but i think he will be able to update changes next week not before.

**Comment by wmdhosting** [comment]
Please can you check with new version if it works ok on your side..

**Comment by handplant** [comment]
In my initial tests, everything is working wonderfully. Thank you very much!
