### ISSUE TITLE
FR: Choose between checkboxes and select field

### ISSUE THREAD

**Issue by chadcrowell** [wmdhosting/craft3-section-and-product-type-field#5]
I'd like the ability to choose in the field settings whether this field displays the sections as a list of checkboxes, as it does now, or a select field type (dropdown) to select just one option. This would be a nice addition if you find time.

**Comment by wmdhosting** [comment]
You now have the option to select just one choice using radio buttons.

![Snag_2d74778](https://github.com/wmdhosting/craft3-section-and-product-type-field/assets/76176291/9d53096a-3d0d-4722-98dd-c6e53d63b07d)

**Comment by chadcrowell** [comment]
Thank you, I appreciate that info. In my case, this is less about being able to select one, or more than one option, and more about the field layout for content authors. [Here's my use case](https://d.pr/i/02sF0S).

**Comment by wmdhosting** [comment]
OK, I was under the impression you had over 50+ sections. :)

It might be worth considering that sometimes visual distinction is more beneficial than trying to compress everything into a minimal space. This approach can help users more quickly understand and navigate the layout.

**Comment by chadcrowell** [comment]
I appreciate you assuming what is best for my client. I'll take that as a no.
